name: globagrim_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - xarray
  - netcdf4
  - matplotlib=3.5.1
  - shapely=1.7.1
  - cartopy=0.18.0
  - jupyter
  - pytest
  - sphinx
  - pip
  - pip:
    - "git+https://github.com/MarcoKulueke/globagrim_project.git#egg=globagrim"
