name: Python test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: globagrim_env
          environment-file: environment.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: Install package
        run: |
          python3 -m pip install .
      - name: Test with pytest
        run: pytest .
